credentials:
  usernames:
    usuario1:
      name: "Carlos Sampaio"
      email: cesampa@gmail.com
      password: '$2b$12$WgqhmVOZyRPbMfXw.FU4uuXILywAzHeU9cgV.xyl/64e8oDs0w9fu'  # bcrypt hash
    usuario2:
      name: "Raquel Sampaio"
      email: rrasampa@gmail.com
      password: '$2b$12$WgqhmVOZyRPbMfXw.FU4uuXILywAzHeU9cgV.xyl/64e8oDs0w9fu'

cookie:
  expiry_days: 30
  key: "chave-muito-secreta"
  name: "meu_cookie_auth"

preauthorized:
  emails:
    - cesampa@gmail.com
    - rrasampa@gmail.com

