[credentials.usernames.usuario1]
email = "cesampa@gmail.com"
name = "Carlos Sampaio"
password = "$2b$12$kQq84Yo5MoR6JgeT2mR3TeX2eB5fki3C7oGBUaTX0qH0xFdySURZy"  # hash de "senha123"

[credentials.usernames.usuario2]
email = "rrasampa@gmail.com"
name = "Raquel Sampaio"
password = "$2b$12$kQq84Yo5MoR6JgeT2mR3TeX2eB5fki3C7oGBUaTX0qH0xFdySURZy"  # hash de "senha456"

[cookie]
expiry_days = 30
key = "um_valor_ultra_secreto_e_unico_para_o_cookie"  # Explico abaixo
name = "auth_cookie"  # Nome técnico do cookie

[preauthorized]
emails = ["cesampa@gmail.com", "rrasampa@gmail.com"]
